# permissions for end users to view labeloperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labeloperator-viewer-role
rules:
- apiGroups:
  - multiple.example.com
  resources:
  - labeloperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multiple.example.com
  resources:
  - labeloperators/status
  verbs:
  - get
