# permissions for end users to edit labeloperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labeloperator-editor-role
rules:
- apiGroups:
  - multiple.example.com
  resources:
  - labeloperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiple.example.com
  resources:
  - labeloperators/status
  verbs:
  - get
