# permissions for end users to view replicasoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicasoperator-viewer-role
rules:
- apiGroups:
  - multiple.example.com
  resources:
  - replicasoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multiple.example.com
  resources:
  - replicasoperators/status
  verbs:
  - get
