# permissions for end users to edit replicasoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicasoperator-editor-role
rules:
- apiGroups:
  - multiple.example.com
  resources:
  - replicasoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiple.example.com
  resources:
  - replicasoperators/status
  verbs:
  - get
