
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - multiple.example.com
  resources:
  - labeloperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiple.example.com
  resources:
  - labeloperators/finalizers
  verbs:
  - update
- apiGroups:
  - multiple.example.com
  resources:
  - labeloperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - multiple.example.com
  resources:
  - replicasoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiple.example.com
  resources:
  - replicasoperators/finalizers
  verbs:
  - update
- apiGroups:
  - multiple.example.com
  resources:
  - replicasoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete 
  - get
  - list
  - watch
  - update